# Copyright (c) 2024, Plinder Development Team
# Distributed under the terms of the Apache License 2.0
from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import biotite.structure as struc
import biotite.structure.io.pdbx as pdbx
import numpy as np
from peppr.contacts import ContactMeasurement

from plinder.core.structure.atoms import _is_hydrogen_isotope
from plinder.core.utils.log import setup_logger

log = setup_logger(__name__)


def get_symmetry_mate_contacts(
    mmcif_filename: Path, contact_threshold: float = 5.0
) -> dict[tuple[str, int], dict[tuple[str, int], dict[int, set[int]]]]:
    """
    Find inter-residue contacts generated by crystallographic symmetry.

    Only contacts involving symmetry mates (not identity) are returned.

    Parameters
    ----------
    mmcif_filename : Path
        Path to mmCIF structure file (supports .gz).
    contact_threshold : float, optional
        Distance cutoff in Angstrom, by default 5.0.

    Returns
    -------
    dict[tuple[str, int], dict[tuple[str, int], dict[int, set[int]]]]
        Mapping of (chain_id, residue_id) to partner residues,
        with atom serials mapped to the symmetry image indices.
    """
    from plinder.data.utils.annotations.cif_utils import read_mmcif_file

    cif_file = read_mmcif_file(mmcif_filename)

    # Build the full unit cell (all symmetry copies)
    try:
        unit_cell = pdbx.get_unit_cell(cif_file, model=1, use_author_fields=False)
    except Exception:
        # No symmetry information (NMR, computational models)
        return {}
    unit_cell = unit_cell[~struc.filter_solvent(unit_cell)]
    unit_cell = unit_cell[~_is_hydrogen_isotope(unit_cell.element)]

    if unit_cell.box is None:
        return {}

    # Get ASU to determine atoms per symmetry copy
    asu = pdbx.get_structure(cif_file, model=1, use_author_fields=False)
    asu = asu[~struc.filter_solvent(asu)]
    asu = asu[~_is_hydrogen_isotope(asu.element)]
    n_asu = len(asu)
    n_total = len(unit_cell)
    if n_total == n_asu:
        return {}
    n_copies = n_total // n_asu

    # Label each atom with its symmetry image index
    image_idx = np.zeros(n_total, dtype=int)
    for i in range(1, n_copies):
        image_idx[i * n_asu : (i + 1) * n_asu] = i

    # Use periodic CellList to find contacts across unit cell boundaries
    cell_list = struc.CellList(
        unit_cell,
        cell_size=contact_threshold,
        periodic=True,
        box=unit_cell.box,
    )

    results: dict[
        tuple[str, int], dict[tuple[str, int], dict[int, set[int]]]
    ] = defaultdict(lambda: defaultdict(lambda: defaultdict(set)))

    # For each atom in the ASU (image 0), find contacts with symmetry mates
    for i in range(n_asu):
        neighbors = cell_list.get_atoms(unit_cell.coord[i], radius=contact_threshold)
        for j in neighbors:
            if j == i or image_idx[j] == 0:
                continue
            c1 = (
                unit_cell.label_asym_id[i]
                if hasattr(unit_cell, "label_asym_id")
                else unit_cell.chain_id[i]
            )
            c2 = (
                unit_cell.label_asym_id[j]
                if hasattr(unit_cell, "label_asym_id")
                else unit_cell.chain_id[j]
            )
            r1 = int(unit_cell.res_id[i]) if unit_cell.res_id[i] else 1
            r2 = int(unit_cell.res_id[j]) if unit_cell.res_id[j] else 1
            atom_serial = i + 1
            results[(c1, r1)][(c2, r2)][atom_serial].add(int(image_idx[j]))

    return results


def get_covalent_connections(
    cif_data: pdbx.CIFBlock,
) -> dict[str, list[tuple[str, str]]]:
    """
    Extract covalent connections from CIF block.

    Parameters
    ----------
    cif_data : pdbx.CIFBlock
        biotite CIF block

    Returns
    -------
    dict[str, list[tuple[str, str]]]
        All covalent links as defined by mmcif annotations
    """
    from plinder.data.utils.annotations.cif_utils import parse_struct_conn

    nucleobase_list = {"A", "C", "U", "G", "DA", "DC", "DG", "DT", "PSU"}
    valid_types = {"covale", "metalc", "hydrog"}

    cov_dict: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for c in parse_struct_conn(cif_data):
        if c["conn_type"] not in valid_types:
            continue
        if c["conn_type"] == "hydrog":
            if c["comp1"].strip() not in nucleobase_list:
                continue
        link1 = ":".join(
            [
                c["auth_seq1"],
                c["comp1"],
                c["chain1"],
                c["seq1"],
                c["atom1"],
            ]
        )
        link2 = ":".join(
            [
                c["auth_seq2"],
                c["comp2"],
                c["chain2"],
                c["seq2"],
                c["atom2"],
            ]
        )
        cov_dict[c["conn_type"]].append((link1, link2))
    return cov_dict


def extract_ligand_links_to_neighbouring_chains(
    all_covalent_dict: dict[str, list[tuple[str, str]]],
    ligand_asym_id: str,
    neighboring_asym_ids: set[str],
    link_type: str = "covale",
) -> set[str]:
    """
    Parse covalant dictionary for a given ligand and its neighbours.

    Parameters
    ----------
    all_covalent_dict : dict[str, list[tuple[str, str]]]
        All covalent links as defined by mmcif annotations
    ligand_asym_id : str
        ligand asymmetric identification string
    neighboring_asym_ids : set[str]
        set of neighbour asymmetric identification strings
    link_type : str, optional
        covalent linkage type in dictionary, by default "covale",
        options include:
            "covale": actual covalent linkage
            "metalc": other dative bond, eg. metal-ligand dative bond
            "hydrogc": strong hydorogen bonding of nucleic acid

    Returns
    -------
    set[str]
        set of covalent linkages in the entry between the ligand and its neighbours

    Notes
    -----
    For the purpose of covalent annotations, we only consider "covale".
    """
    covalent_linkages = set()
    if link_type in all_covalent_dict:
        for link1, link2 in all_covalent_dict[link_type]:
            chain1, chain2 = link1.split(":")[2], link2.split(":")[2]
            chains = {chain1, chain2}
            if len(chains) == 1:
                # remove linkages that are to the same chain!
                continue
            if set(chains).intersection(ligand_asym_id):
                # only if ligand is involved
                # now check that one chain is neighbour and the other is ligand
                # enforce receptor_ligand ordering
                if neighboring_asym_ids.intersection([chain1]) and set(
                    [chain2]
                ).intersection(ligand_asym_id):
                    covalent_linkages.add(f"{link1}__{link2}")
                elif neighboring_asym_ids.intersection(chain2) and set(
                    [chain1]
                ).intersection(ligand_asym_id):
                    covalent_linkages.add(f"{link2}__{link1}")
    return covalent_linkages


def run_peppr_interactions(
    receptor: struc.AtomArray,
    ligand: struc.AtomArray,
    waters: struc.AtomArray,
    metals: struc.AtomArray,
    ligand_chain: str,
    chain_mapping: dict[str, str],
) -> tuple[dict[str, dict[int, list[str]]], set[tuple[str, int]]]:
    """Compute interaction hash using peppr ContactMeasurement.

    Parameters
    ----------
    receptor : AtomArray
        Receptor heavy atoms.
    ligand : AtomArray
        Ligand heavy atoms.
    waters : AtomArray
        Water heavy atoms.
    metals : AtomArray
        Metal ion heavy atoms (used for metal bridge detection).
    ligand_chain : str
        Ligand chain identifier ({instance}.{chain}).
    chain_mapping : dict[str, str]
        Identity mapping over the chain IDs already in
        ``{instance}.{chain}`` form (kept as a parameter for legacy
        reasons; callers pass ``{c: c for c in np.unique(...)}``).

    Returns
    -------
    interaction_hashes : dict
        {instance.chain: {residue_number: [interaction_strings]}}
    water_set : set
        {(instance.chain, residue_number)} of bridging waters.
    """
    interaction_hashes: dict[str, dict[int, list[str]]] = {}
    water_set: set[tuple[str, int]] = set()

    try:
        cm = ContactMeasurement(receptor, ligand)
    except Exception as e:
        log.warning(f"run_peppr_interactions: ContactMeasurement failed: {e}")
        return interaction_hashes, water_set

    def _add(chain: str, resnr: int, attr: str) -> None:
        if chain == ligand_chain:
            return
        if chain not in interaction_hashes:
            interaction_hashes[chain] = {}
        if resnr not in interaction_hashes[chain]:
            interaction_hashes[chain][resnr] = []
        interaction_hashes[chain][resnr].append(attr)

    _PROTEIN_MAINCHAIN = {"N", "CA", "C", "O"}
    _NA_MAINCHAIN = {"P", "O5'", "C5'", "C4'", "C3'", "O3'"}
    _mainchain_mask = (
        np.isin(receptor.atom_name, list(_PROTEIN_MAINCHAIN))
        & struc.filter_amino_acids(receptor)
    ) | (
        np.isin(receptor.atom_name, list(_NA_MAINCHAIN))
        & struc.filter_nucleotides(receptor)
    )

    def _is_sidechain(atom_idx: int) -> bool:
        return not _mainchain_mask[atom_idx]

    # H-bonds
    try:
        rec_donates, lig_donates = cm.find_hbonds()
        for ri, _li in rec_donates:
            c = chain_mapping.get(receptor.chain_id[ri], receptor.chain_id[ri])
            sc = _is_sidechain(ri)
            _add(
                c,
                int(receptor.res_id[ri]),
                f"type:hydrogen_bonds__protisdon:True__sidechain:{sc}",
            )
        for ri, _li in lig_donates:
            c = chain_mapping.get(receptor.chain_id[ri], receptor.chain_id[ri])
            sc = _is_sidechain(ri)
            _add(
                c,
                int(receptor.res_id[ri]),
                f"type:hydrogen_bonds__protisdon:False__sidechain:{sc}",
            )
    except Exception as e:
        log.warning(f"run_peppr_interactions: find_hbonds failed: {e}")

    # Salt bridges
    try:
        salt_bridges = cm.find_salt_bridges()
        for ri, _li in salt_bridges:
            c = chain_mapping.get(receptor.chain_id[ri], receptor.chain_id[ri])
            _add(c, int(receptor.res_id[ri]), "type:salt_bridges__protispos:True")
    except Exception as e:
        log.warning(f"run_peppr_interactions: find_salt_bridges failed: {e}")

    # Pi-stacking (deduplicate per residue)
    try:
        from biotite.structure import PiStacking

        stacking = cm.find_stacking_interactions()
        seen_stacking: set[tuple[str, int, str]] = set()
        for rec_idx, _lig_idx, stack_type in stacking:
            ri = rec_idx[0]
            c = chain_mapping.get(receptor.chain_id[ri], receptor.chain_id[ri])
            stype = "T" if stack_type == PiStacking.PERPENDICULAR else "P"
            key = (c, int(receptor.res_id[ri]), stype)
            if key not in seen_stacking:
                seen_stacking.add(key)
                _add(c, int(receptor.res_id[ri]), f"type:pi_stacks__stack_type:{stype}")
    except Exception as e:
        log.warning(f"run_peppr_interactions: find_stacking_interactions failed: {e}")

    # Pi-cation
    try:
        pi_cation = cm.find_pi_cation_interactions()
        for rec_idx, _lig_idx, cation_in_receptor in pi_cation:
            ri = rec_idx[0]
            c = chain_mapping.get(receptor.chain_id[ri], receptor.chain_id[ri])
            if cation_in_receptor:
                _add(
                    c,
                    int(receptor.res_id[ri]),
                    "type:pi_cation__lig_group:Aromatic__protcharged:True",
                )
            else:
                _add(
                    c,
                    int(receptor.res_id[ri]),
                    "type:pi_cation__lig_group:Cation__protcharged:False",
                )
    except Exception as e:
        log.warning(f"run_peppr_interactions: find_pi_cation_interactions failed: {e}")

    # Halogen bonds
    try:
        from peppr.common import (
            ACCEPTOR_PATTERN,
            HALOGEN_DISTANCE_SCALING,
            HALOGEN_PATTERN,
        )

        halogen_bonds = cm.find_contacts_by_pattern(
            ACCEPTOR_PATTERN,
            HALOGEN_PATTERN,
            HALOGEN_DISTANCE_SCALING,
        )
        for ri, _li in halogen_bonds:
            c = chain_mapping.get(receptor.chain_id[ri], receptor.chain_id[ri])
            sc = _is_sidechain(ri)
            _add(c, int(receptor.res_id[ri]), f"type:halogen_bonds__sidechain:{sc}")
    except Exception as e:
        log.warning(f"run_peppr_interactions: halogen_bonds failed: {e}")

    # Water bridges (via plinder patch — peppr public doesn't have this yet)
    try:
        if waters.array_length() > 0:
            from peppr.common import DONOR_PATTERN
            from peppr.contacts import find_atoms_by_pattern

            from plinder.data.utils.annotations.cif_utils import find_water_bridges

            receptor_donors = set(
                find_atoms_by_pattern(cm._binding_site_mol, DONOR_PATTERN)
            )
            w_bridges = find_water_bridges(receptor, ligand, waters)
            for rec_idx, _lig_idx, water_idx in w_bridges:
                ri = rec_idx[0]
                wi = water_idx[0]
                # Check if receptor atom is a donor
                bs_idx = None
                for j, orig_idx in enumerate(cm._binding_site_indices):
                    if orig_idx == ri:
                        bs_idx = j
                        break
                protisdon = bs_idx in receptor_donors if bs_idx is not None else True
                c = chain_mapping.get(receptor.chain_id[ri], receptor.chain_id[ri])
                _add(
                    c,
                    int(receptor.res_id[ri]),
                    f"type:water_bridges__protisdon:{protisdon}",
                )
                w_chain = chain_mapping.get(waters.chain_id[wi], waters.chain_id[wi])
                water_set.add((w_chain, int(waters.res_id[wi])))
    except Exception as e:
        log.warning(f"run_peppr_interactions: find_water_bridges failed: {e}")

    # Metal bridges (via plinder patch — peppr public doesn't have this yet)
    try:
        if metals.array_length() > 0:
            from plinder.data.utils.annotations.cif_utils import find_metal_bridges

            m_bridges = find_metal_bridges(receptor, ligand, metals)
            for rec_idx, _lig_idx, metal_idx in m_bridges:
                ri = rec_idx[0]
                mi = metal_idx[0]
                c = chain_mapping.get(receptor.chain_id[ri], receptor.chain_id[ri])
                metal_elem = metals.element[mi]
                _add(
                    c,
                    int(receptor.res_id[ri]),
                    f"type:metal_complexes__metal_type:{metal_elem}",
                )
    except Exception as e:
        log.warning(f"run_peppr_interactions: find_metal_bridges failed: {e}")

    return interaction_hashes, water_set
