flow:
  run_specific_stages: collate_partitions,make_component_reductions,merge_component_reductions,make_communities,summarize_clusters,finalize_index
  make_components_force_update: true
data:
  plinder_mount: /plinder
  plinder_release: 2024-06
  plinder_iteration: v3
