flow:
  run_specific_stages: make_entries,collate_entries,make_canonical_ligand_archives,compute_ligand_fingerprints,make_ligand_scores,annotate_ligand_similarity
  download_rcsb_files_batch_size: 1
  make_entries_batch_size: 120
  make_ligands_batch_size: 220
data:
  plinder_mount: /plinder
  plinder_release: 2024-06
  plinder_iteration: v3
