name: Package
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  publish:
    name: Package
    if: ${{ ! contains(toJSON(github.event.commits.*.message), '[skip ci]') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          create-args: python=3.12
          init-shell: bash
          cache-downloads: true
          cache-environment: true
          post-cleanup: all
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install plinder
        run: UV_PROJECT_ENVIRONMENT="$CONDA_PREFIX" uv sync --inexact
      - name: Get version bump
        id: get-tag
        run: echo "bump=$(python flows/version.py)" >> $GITHUB_OUTPUT
      - name: Run tests
        if: steps.get-tag.outputs.bump != ''
        env:
          PLINDER_OFFLINE: "true"
        run: python -m pytest -n auto -v
      - name: Tag release
        if: steps.get-tag.outputs.bump != ''
        run: git tag ${{ steps.get-tag.outputs.bump }}
      - name: Build distribution
        run: uv build
      - name: Publish package distributions to PyPI
        if: steps.get-tag.outputs.bump != ''
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Save git tag
        if: steps.get-tag.outputs.bump != ''
        run: git push origin ${{ steps.get-tag.outputs.bump }}
      - name: Post coverage comment
        if: steps.get-tag.outputs.bump != ''
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
